### PR TITLE
feat: add Docker Secrets support

### LINKED ISSUE #197: Add Docker Secrets support
**Is your feature request related to a problem? Please describe.**

Docker Secrets provides secrets to containers through files. TTRSS' Docker Image only reads from environment variables directly, thus lacking Docker Secrets support.

**Describe the solution you'd like**

Take on the documentation's [suggestion](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images) and add support for `DB_USER_FILE` and `DB_PASS_FILE` to env vars and read from them like the Wordpress image [does](https://github.com/docker-library/wordpress/blob/b1127748deb2db34e9b1306489e24eb49720454f/php7.2/apache/docker-entrypoint.sh).

### PR DESCRIPTION
**Pull request by abelfodil**
Add the `DB_USER_FILE` and `DB_PASS_FILE` env vars to read DB credentials from files (and Docker Secrets).

Closes #197

### CODE REVIEW

**Comment by HenryQW** [comment]
Did some readings on this, it seems docker-compose is not fully compatible with secrets, at least not in non-swarm mode.

[One solution](https://serverfault.com/questions/871090/how-to-use-docker-secrets-without-a-swarm-cluster) to it:
```
secrets:
  DB_USER_FILE:
    file: ./DB_USER_FILE.txt
  DB_PASS_FILE:
    file: ./DB_PASS_FILE.txt
```
Which is not something I'd use consider the extra complexity, you need to add codes in the entrypoint, modify the compose file and documentation.

The repo aims to serve novice users, I don't expect them to learn these.

**Comment by abelfodil** [comment]
I made the changes following your suggestions.

Here's a working [example](https://github.com/arch-anes/self-hosted-services/blob/secrets/stacks/ttrss/docker-compose.yml) using Docker Swarm. Should I also document it?

Btw I don't speak chinese, so I can't update the zh doc :(

**Comment by HenryQW** [comment]
Depends, is there a way to simplify the generation of docker secrets, so that novice users don't have to get their hands dirty?

There are many 'best practices' in terms of docker-compose security, but for novice users I think using ENV is the most straightforward way. Storing passwords in .txt somewhere on their servers hardly provide any advantage, let alone the extra configs they will have to google.

As an advanced user, you are always welcome to modify your own docker-compose file :)

**Comment by HenryQW** [comment]
Your traefik setup looks very interesting, does that automate everything for ttrss including reverse proxy?

**Comment by abelfodil** [comment]
> Depends, is there a way to simplify the generation of docker secrets, so that novice users don't have to get their hands dirty?

I use `openssl rand -base64 40 | docker secret create secret_name -` to generate my "external" secrets. I think that's as simple as it can get in terms of Docker Secrets.

> There are many 'best practices' in terms of docker-compose security, but for novice users I think using ENV is the most straightforward way. Storing passwords in .txt somewhere on their servers hardly provided any advantage, let alone the extra configs they will have to google.
> As an advanced user, you are always welcome to modify your own docker-compose file :)

I think that's a reasonable stance.

> Your traefik setup looks very interesting, does that automate everything for ttrss including reverse proxy?

Yes, thanks to Ansible : 
- I run `ansible-playbook 01_setup_hosts.yml` when I want to add a new machine to the cluster or set it up from scratch
- I run the secret generation command if I need to add a new secret to the cluster
- I run `ansible-playbook 02_deploy_stacks.yml` and it automatically deploys Traefik and the other services to my home cluster. Traefik then automatically secures each service by looking at the deployment labels. For now, the domain name is harcoded [here](https://github.com/arch-anes/self-hosted-services/blob/secrets/group_vars/all/common.yml#L5) and passed to the containers.

**Comment by abelfodil** [comment]
@HenryQW any other thoughts?

**Comment by HenryQW** [comment]
I have added `docker networks` support, I don't think adding file-based secret support is valuable, especially it adds extra complexity to novice users.

**Comment by abelfodil** [comment]
I can remove the example to not confuse novice users, but file-based secret support is **necessary** for Docker Secrets to work.

**Comment by HenryQW** [comment]
If we add the docker-compose.secrets.yml as an example, it won't be maintained, managing multiple compose files is challenging. 

We should just mention the support in the doc.

**Comment by abelfodil** [comment]
Done

**Comment by HenryQW** [comment]
Thanks for your contribution!

**Pull request merged**
