### PR TITLE
Support LOG_DESTINATION env var

### PR DESCRIPTION
**Pull request by vfauth**
Juste exposed two more settings via environment variables.

### CODE REVIEW

**Comment by HenryQW** [comment]
Hi I'm very opinionated about not using MySQL, I actually removed it from this repo years ago.

**Comment by vfauth** [comment]
Well, I can perfectly understand that, but why not let users choose? Some of them may have already a MySQL DB.

But I mainly wanted to support LOG_DESTINATION and added DB_TYPE as a bonus, so I can remove it if you wish.

**Comment by HenryQW** [comment]
Even the author of TTRSS downplays the use of MySQL, and I didn't have a good experience with it too. https://github.com/HenryQW/Awesome-TTRSS/issues/91#issuecomment-558396887

You can reimplement it in `configure-db.php`, there are several places need work. You will have to test the stack out to prove it's working stably and also completes the documentation.

**Comment by vfauth** [comment]
I was only thinking about people using the image standalone (many people use it as a replacement for the deprecated LinuxServer.io ttrss image), I certainly don't have the motivation to convert the whole stack to MySQL.

**Comment by vfauth** [comment]
I removed the DB_TYPE env var.

**Comment by HenryQW** [comment]
Thanks!

**Pull request merged**
