### PR TITLE
feat: support php8

### PR DESCRIPTION
**Pull request by oppilate**
### Why

Fixes https://github.com/HenryQW/Awesome-TTRSS/issues/242. A couple of performance and security improvements.

### Why

[Some hardening](https://github.com/docker-library/php/blob/57143cba9161c913cae8ba0a985bc30ba35130d2/8.0/alpine3.13/fpm/Dockerfile#L57) won't exist be enforced you simply install php yourself. And it's not reasonable to implement all those again.

### Why

Many image registries are emerging these days (e.g. quay.io). Some, container orchistrators, e.g. podman, don't assume the images being hosted in `docker.io` by default, which is fair. Adding this prefix makes the reference more clear, and you don't have to select the registry every time.

## TODO

- The image grows to 205 MB, and that's not satisfying. Maybe we need to analyze the image in some way
- The homepage is not going to load

### CODE REVIEW

**Comment by HenryQW** [comment]
what do you mean by `The homepage is not going to load`?

**Comment by HenryQW** [comment]
The image size on dockerhub is only increased by 12MB, presumably due to those new PHP extensions, webp etc., I think this is acceptable. Also I don't have the homepage not loading issue.

Thanks for your contribution.

**Comment by oppilate** [comment]
> ``?

That's fixed. I forgot to mention. The reasons was the feed fetching job took too much time, and php only have 5 workers by default. So no worker for me to load the page.

**Comment by HenryQW** [comment]
I will have to re-merge this when things are dusted. Too many changes from TTRSS recently.

**Comment by oppilate** [comment]
I see and no problem :)

**Comment by HenryQW** [comment]
#264 upgraded the image to php8, rather than building locally it installs pre-built libraries which is a lot faster to build the image. Extensions should also work flawlessly, as far as my test says.

**Comment by HenryQW** [comment]
Yeah just checked, php8-gd pre-built already compiled everything, happy days.
image

**Pull request merged**
